Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05572e392e80aee89 # Replace with a valid AMI ID for your region
      SubnetId: !ImportValue us-west-2-MyVPCStack-PublicSubnet0
      SecurityGroupIds:
        - !ImportValue us-west-2-MyVPCStack-DefaultSecurityGroup
      KeyName: key-name-2 # Replace with your EC2 key pair name
      Tags:
        - Key: Name
          Value: MyEC2Instance